# Bottlerocket - kubelet TLS bootstrap config for Steward TCP
# TCP: trustd-test at 10.40.0.214:6443 (v1.30.2)
#
# Bottlerocket does NOT use kubeadm. Kubelet is configured directly
# via settings.kubernetes.* and performs TLS bootstrapping using
# the bootstrap token to authenticate with the API server.
#
# Image: bottlerocket-metal-k8s-1.30 variant
# Download: https://updates.bottlerocket.aws/targets/
# Convert: unlz4 image.lz4 && qemu-img convert -f raw -O qcow2 image.img image.qcow2
#
# This TOML is written to partition 12 (BOTTLEROCKET-PRIVATE) as user-data.toml

[settings.kubernetes]
api-server = "https://10.40.0.214:6443"
cluster-certificate = "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJVTdaOHkzMzViZEl3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBeU1URXlNREkxTkRsYUZ3MHpOakF5TURreU1ETXdORGxhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUN5T2ErZGJjRlVzd1pMMDhDdXh5YWVWS1VRQkluYlBMQks0YTgyYzhndW9OVzREUVlYalgyc2RlTnoKY2xmWloweDZubWtEZGNFU3R4d2duMkRWeHRhZUowVFNJYzZTdkRVYU0ydHY4OTFhMjN4bTUrQkM2U3hGdTVRRApEbHIwdmFkWXNOaHBKNnlLZFZBVDJzbHNNTGhYcnFqYnE4cjNNNWxaVU1UcHkvRk1kZjFYUUVsbGNzSG9TTEtYClk4U0FqZ3VDY05rVXBBY25PVC9XR0g3SFZKbVJ5RlpmbjBoUzBIVXNQSkZ4MmhTWW5RbWRMN1VKcEpMYlliTG4KbnFXT05FUTBwVXFDUFRRZG00YUpiTHQvQk5ZM0xXZWxpWDNPcmlMSDZWNkpKOVZtQytGTkdlWGJMcjRRaVBqMApLbml2cFluMEF5ZzBzREg5SWM4cXltUGNwVXFsQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUaEZ1ZGxrZjhnNkd0VUdtdlJkVUlaOWhlWUt6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQUlNRGFnSXo5cgpGc2JFR2kwTGt2Nm1FUERTVndodUJFaU9Nbmp1Nkx3UjhZaTFXam9JMkpYM3UzZUtDVHRBMVdSYmVBbHNiSklkClVTOFVSMHlMaklXUWxpMjZDZjFndVg4NWEvZlNJWWVwN0pKSFFXWEtVRzQxNXU1cithM1BFSFluY3gvSFMzclkKVnQwZXd1c2pOaTVhbmpQRW04UTNsS0l3TG1oakRaN3BrMzdueWdtSE9qV2E3WlluYXJSaWI2MUlrZXpIaEVXYgpzV3Urc2oxRnJLVW1ORFZxNmFoTzNVbVo1TkVYZHdHdkplTkpHWHp3Smo0dUFjSG53M25qYmV6VTJYQ1N2R0xwCnBtTUx0a2tHNjEwZVhrSlR3QjJvR2RrdHlaeHJBMGVqUkhwOUNCVmVkT3hEQTVnWGpHaEp0d1dvS2lndjNHOTkKT2VLOG14eTA0ZUY2Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
cluster-name = "trustd-test"
authentication-mode = "tls"
bootstrap-token = "13c53e.fb7d6c11b1ea9d8d"
cluster-domain = "cluster.local"
